import { features } from "../config";
import { publicRoutes } from "../seo/routes";
import { redirectMap, redirects } from "../seo/redirects";

const routes = publicRoutes(features);
const map = redirects(routes);

describe("legacy URL redirects", () => {
  it("never repeats a key — nginx refuses to start on a duplicate", () => {
    const keys = [...map.keys()];
    expect(new Set(keys).size).toBe(keys.length);
  });

  it("never sends a URL to itself", () => {
    for (const [from, to] of map) expect(from).not.toBe(to);
  });

  it("covers the old English slug under every language segment", () => {
    expect(map.get("/de/prices")).toBe("/de/preise");
    expect(map.get("/uk/prices")).toBe("/uk/%D1%86%D1%96%D0%BD%D0%B8");
    expect(map.get("/ru/package-terms")).toBe(
      `/ru/${encodeURIComponent("условия-пакетов")}`,
    );
    expect(map.get("/de/terms")).toBe("/de/agb");
  });

  it("covers the pre-rename /privacy and the English /datenschutz", () => {
    expect(map.get("/de/privacy")).toBe("/de/datenschutz");
    expect(map.get("/en/datenschutz")).toBe("/en/privacy");
    expect(map.get("/privacy")).toBe("/de/datenschutz");
  });

  it("sends the unprefixed paths to the default language", () => {
    expect(map.get("/prices")).toBe("/de/preise");
    expect(map.get("/imprint")).toBe("/de/impressum");
    expect(map.get("/for-whom/beard-contour")).toBe("/de/fuer-wen/klare-bartkontur");
  });

  it("leaves the root alone — it is a real file and picks the language itself", () => {
    expect(map.has("/")).toBe(false);
  });

  it("never redirects a URL the site currently serves", () => {
    // A key that is also a live page would take the page off the air.
    const live = new Set(
      routes.flatMap((route) =>
        (["de", "en", "uk", "ru"] as const).map((language) => `/${language}${
          route.slugs[language] === "/" ? "" : route.slugs[language]
        }`),
      ),
    );
    for (const from of map.keys()) expect(live.has(from)).toBe(false);
  });

  it("writes an nginx map file with one quoted pair per line", () => {
    const body = redirectMap(routes);
    expect(body.startsWith("# Generated by")).toBe(true);
    expect(body).toContain('"/de/prices" "/de/preise";\n');
    expect(body.endsWith("\n")).toBe(true);
    for (const line of body.trim().split("\n")) {
      expect(line).toMatch(/^(#.*|"[^"]+" "[^"]+";)$/);
    }
  });

  it("leaves out anything pointing at a flagged-off route", () => {
    expect([...map.keys()].some((from) => from.endsWith("/booking"))).toBe(false);
  });
});
