import { defaultLanguage, supportedLanguages } from "../i18n/routing";
import { legacyRedirects, localizedRoutePath } from "./routePaths";
import type { SiteRoute } from "./routes";

/**
 * Every URL the site used to serve, mapped to the one it serves now.
 *
 * Three generations of URL end up in here:
 *   - the English slug under each language segment (`/uk/prices`), from
 *     before the slugs were localized,
 *   - `/privacy`, from before the privacy policy became `/datenschutz`,
 *   - the unprefixed paths (`/prices`), from before the language segments
 *     existed at all.
 *
 * An unprefixed path cannot know the visitor's language, so it goes to the
 * default one: a 301 to a real page carrying the full hreflang set beats
 * both a 404 and a 200 that only JavaScript can resolve. Bare `/` is not in
 * here — it is a real file, and the router picks the language there.
 *
 * Generated rather than hand-kept for the same reason as the sitemap: a
 * list of 40-odd redirects maintained by hand is wrong within a month.
 */
export function redirects(routes: readonly SiteRoute[]): Map<string, string> {
  const map = new Map<string, string>();

  const add = (from: string, to: string) => {
    // First writer wins, and a path never redirects to itself — nginx
    // refuses to start on a duplicate map key, and a self-redirect is an
    // infinite loop in a browser.
    if (from === to || map.has(from)) return;
    map.set(from, to);
  };

  for (const language of supportedLanguages) {
    for (const { from, to } of legacyRedirects(language, routes)) {
      add(`/${language}/${from}`, to);
    }
  }

  for (const { from, to } of legacyRedirects(defaultLanguage, routes)) {
    add(`/${from}`, to);
  }
  for (const route of routes) {
    if (route.path === "/") continue;
    add(route.path, localizedRoutePath(defaultLanguage, route.path));
  }

  return map;
}

/** The same thing as an nginx `map` body, for `dist/_redirects.map`. */
export function redirectMap(routes: readonly SiteRoute[]): string {
  const lines = [
    "# Generated by client/vite/seoPrerender.ts — do not edit by hand.",
    "# Included by docker/nginx.conf into `map $uri $legacy_target`.",
    ...[...redirects(routes)].map(([from, to]) => `"${from}" "${to}";`),
  ];
  return `${lines.join("\n")}\n`;
}
