import { supportedLanguages } from "../i18n/routing";
import { alternateLinks, canonicalUrl } from "./meta";
import type { SiteRoute } from "./routes";

/**
 * The sitemap, generated rather than hand-written.
 *
 * It is the route table times `supportedLanguages` — 36 <url> entries with
 * four languages — each carrying the full alternate set; keeping that in
 * sync with the route table by hand was never going
 * to work, so `vite/seoPrerender.ts` writes it into `dist/` at build time
 * and the dev server serves the same string. `src/test/sitemap.test.ts`
 * asserts the output against the route table.
 *
 * Every URL declares the full hreflang set (including itself, as the spec
 * requires) so Google can group every translation of a page as one
 * cluster instead of competing near-duplicates.
 *
 * `routes` is `publicRoutes(features)`, not the raw table: a route hidden
 * behind an off feature flag must not be advertised to crawlers.
 */
export function buildSitemap(lastmod: string, routes: readonly SiteRoute[]): string {
  const entries = routes.flatMap((route) =>
    supportedLanguages.map((language) => {
      const alternates = alternateLinks(route.path)
        .map(
          (alternate) =>
            `    <xhtml:link rel="alternate" hreflang="${alternate.hreflang}" href="${alternate.href}" />`,
        )
        .join("\n");
      return [
        "  <url>",
        `    <loc>${canonicalUrl(language, route.path)}</loc>`,
        alternates,
        `    <lastmod>${lastmod}</lastmod>`,
        `    <changefreq>${route.changefreq}</changefreq>`,
        `    <priority>${route.priority}</priority>`,
        "  </url>",
      ].join("\n");
    }),
  );

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    "<!--",
    "  Generated by client/vite/seoPrerender.ts from src/seo/routes.ts and the",
    "  language list in src/i18n/routing.ts — do not edit by hand.",
    "-->",
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
    '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
    ...entries,
    "</urlset>",
    "",
  ].join("\n");
}
